
#  API 配置（支持多个 API 提供者，格式：name|url|token，逗号分隔）
# name: API 名称（用于日志显示）
# url: API 地址
# token: 认证 Token
readwise.api.config=*****

# 目标推送地址（支持多个，用,分割）
webhook.target.url=********

# 定时任务配置
scheduler.hour=8
scheduler.minute=30
scheduler.second=0

# 内容配置
summary.max.length=300
news.max.count=3
