# Readwise API 配置
readwise.api.url=https://readwise.io/api/v3/list/
readwise.api.token=*****

# 目标推送地址
webhook.target.url=****

# 定时任务配置
scheduler.hour=8
scheduler.minute=30
scheduler.second=0

# 内容配置
summary.max.length=300
news.max.count=3
